spring:
  redis:
    database: 11
    host: localhost
    port: 6379
    password: 123456     # 密码（默认为空）
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 1000ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
    shutdown-timeout: 50000ms